
import { useState, useCallback } from 'react';
import { Consultant } from '../types/consultant';

export const useConsultants = () => {
  const [consultants] = useState<Consultant[]>([
    {
      id: '1',
      name: 'Erik Andersson',
      email: 'erik.andersson@example.com',
      phone: '+46 70 123 4567',
      location: 'Stockholm, Sweden',
      title: 'Senior Frontend Developer',
      tagline: 'React specialist with 8 years of experience',
      skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'AWS'],
      roles: ['Frontend Developer', 'Full-stack Developer'],
      experience: '8 years',
      experience_years: 8,
      certifications: ['AWS Certified Developer', 'React Professional'],
      languages: ['Swedish', 'English', 'German'],
      rating: 4.8,
      projects: 23,
      rate: '850 SEK/hour',
      hourly_rate: 850,
      availability: 'Available from January 2025',
      lastActive: 'Today',
      last_active: 'Today',
      cv: '',
      communicationStyle: 'Direct and collaborative',
      communication_style: 'Direct and collaborative',
      workStyle: 'Agile and iterative',
      work_style: 'Agile and iterative',
      teamFit: 'Works well in cross-functional teams',
      team_fit: 'Works well in cross-functional teams',
      culturalFit: 4,
      cultural_fit: 4,
      adaptability: 5,
      leadership: 3,
      personalityTraits: ['Analytical', 'Creative', 'Detail-oriented'],
      personality_traits: ['Analytical', 'Creative', 'Detail-oriented'],
      values: ['Innovation', 'Team Collaboration', 'Continuous Learning'],
      linkedin_url: 'https://linkedin.com/in/erik-andersson',
      thought_leadership_score: 7.5,
      type: 'existing',
      created_at: '2024-01-01',
      updated_at: '2024-01-15',
      visibility_status: 'public',
      is_published: true,
      industries: ['Technology', 'E-commerce']
    },
    {
      id: '2',
      name: 'Anna Johansson',
      email: 'anna.johansson@example.com',
      phone: '+46 73 987 6543',
      location: 'Gothenburg, Sweden',
      title: 'Backend Developer',
      tagline: 'Python and cloud architecture expert',
      skills: ['Python', 'Django', 'PostgreSQL', 'Docker', 'Kubernetes'],
      roles: ['Backend Developer', 'DevOps Engineer'],
      experience: '6 years',
      experience_years: 6,
      certifications: ['AWS Solutions Architect', 'Google Cloud Professional'],
      languages: ['Swedish', 'English'],
      rating: 4.9,
      projects: 18,
      rate: '920 SEK/hour',
      hourly_rate: 920,
      availability: 'Available',
      lastActive: '2 days ago',
      last_active: '2 days ago',
      cv: '',
      communicationStyle: 'Thoughtful and precise',
      communication_style: 'Thoughtful and precise',
      workStyle: 'Independent with regular check-ins',
      work_style: 'Independent with regular check-ins',
      teamFit: 'Mentors junior developers effectively',
      team_fit: 'Mentors junior developers effectively',
      culturalFit: 4,
      cultural_fit: 4,
      adaptability: 4,
      leadership: 4,
      personalityTraits: ['Logical', 'Patient', 'Methodical'],
      personality_traits: ['Logical', 'Patient', 'Methodical'],
      values: ['Quality', 'Problem Solving', 'Innovation'],
      linkedin_url: 'https://linkedin.com/in/anna-johansson',
      thought_leadership_score: 8.2,
      type: 'existing',
      created_at: '2024-01-02',
      updated_at: '2024-01-16',
      visibility_status: 'public',
      is_published: true,
      industries: ['Fintech', 'Healthcare']
    },
    {
      id: '3',
      name: 'Marcus Lindberg',
      email: 'marcus.lindberg@example.com',
      phone: '+46 76 555 1234',
      location: 'Malmö, Sweden',
      title: 'Full Stack Developer',
      tagline: 'Vue.js and Node.js specialist',
      skills: ['Vue.js', 'JavaScript', 'Node.js', 'MongoDB', 'Express'],
      roles: ['Full-stack Developer', 'Frontend Developer'],
      experience: '5 years',
      experience_years: 5,
      certifications: ['Vue.js Certified', 'MongoDB Professional'],
      languages: ['Swedish', 'English', 'Danish'],
      rating: 4.7,
      projects: 15,
      rate: '780 SEK/hour',
      hourly_rate: 780,
      availability: 'Available from February 2025',
      lastActive: '1 day ago',
      last_active: '1 day ago',
      cv: '',
      communicationStyle: 'Clear and structured',
      communication_style: 'Clear and structured',
      workStyle: 'Component-driven development',
      work_style: 'Component-driven development',
      teamFit: 'Collaborative problem solver',
      team_fit: 'Collaborative problem solver',
      culturalFit: 5,
      cultural_fit: 5,
      adaptability: 4,
      leadership: 3,
      personalityTraits: ['Strategic', 'Collaborative', 'Results-driven'],
      personality_traits: ['Strategic', 'Collaborative', 'Results-driven'],
      values: ['Scalability', 'Performance', 'Team Leadership'],
      linkedin_url: 'https://linkedin.com/in/marcus-lindberg',
      thought_leadership_score: 6.8,
      type: 'existing',
      created_at: '2024-01-03',
      updated_at: '2024-01-17',
      visibility_status: 'public',
      is_published: true,
      industries: ['SaaS', 'Media']
    },
    {
      id: '4',
      name: 'Sara Karlsson',
      email: 'sara.karlsson@example.com',
      phone: '+46 70 444 5555',
      location: 'Uppsala, Sweden',
      title: 'DevOps Engineer',
      tagline: 'Cloud infrastructure and automation expert',
      skills: ['AWS', 'Terraform', 'Docker', 'Kubernetes', 'Python'],
      roles: ['DevOps Engineer', 'Cloud Architect'],
      experience: '7 years',
      experience_years: 7,
      certifications: ['AWS Solutions Architect', 'Terraform Associate'],
      languages: ['Swedish', 'English'],
      rating: 4.8,
      projects: 22,
      rate: '950 SEK/hour',
      hourly_rate: 950,
      availability: 'Available',
      lastActive: 'Today',
      last_active: 'Today',
      cv: '',
      communicationStyle: 'Professional and supportive',
      communication_style: 'Professional and supportive',
      workStyle: 'Infrastructure as Code focused',
      work_style: 'Infrastructure as Code focused',
      teamFit: 'Excellent team player and knowledge sharer',
      team_fit: 'Excellent team player and knowledge sharer',
      culturalFit: 5,
      cultural_fit: 5,
      adaptability: 4,
      leadership: 4,
      personalityTraits: ['Systematic', 'Reliable', 'Innovative'],
      personality_traits: ['Systematic', 'Reliable', 'Innovative'],
      values: ['Code Quality', 'Automation', 'Team Collaboration'],
      linkedin_url: 'https://linkedin.com/in/sara-karlsson',
      thought_leadership_score: 8.5,
      type: 'existing',
      created_at: '2024-01-04',
      updated_at: '2024-01-18',
      visibility_status: 'public',
      is_published: true,
      industries: ['Cloud Computing', 'Fintech']
    },
    {
      id: '5',
      name: 'Johan Svensson',
      email: 'johan.svensson@example.com',
      phone: '+46 72 666 7777',
      location: 'Linköping, Sweden',
      title: 'Mobile Developer',
      tagline: 'React Native and Flutter specialist',
      skills: ['React Native', 'Flutter', 'JavaScript', 'Dart', 'Firebase'],
      roles: ['Mobile Developer', 'Cross-platform Developer'],
      experience: '4 years',
      experience_years: 4,
      certifications: ['React Native Certified', 'Flutter Professional'],
      languages: ['Swedish', 'English', 'Finnish'],
      rating: 4.6,
      projects: 12,
      rate: '720 SEK/hour',
      hourly_rate: 720,
      availability: 'Available from March 2025',
      lastActive: '3 days ago',
      last_active: '3 days ago',
      cv: '',
      communicationStyle: 'Friendly and clear',
      communication_style: 'Friendly and clear',
      workStyle: 'Mobile-first development approach',
      work_style: 'Mobile-first development approach',
      teamFit: 'Great collaborator and problem solver',
      team_fit: 'Great collaborator and problem solver',
      culturalFit: 4,
      cultural_fit: 4,
      adaptability: 5,
      leadership: 3,
      personalityTraits: ['Creative', 'Adaptable', 'User-focused'],
      personality_traits: ['Creative', 'Adaptable', 'User-focused'],
      values: ['User Experience', 'Clean Code', 'Continuous Learning'],
      linkedin_url: 'https://linkedin.com/in/johan-svensson',
      thought_leadership_score: 6.2,
      type: 'existing',
      created_at: '2024-01-05',
      updated_at: '2024-01-19',
      visibility_status: 'public',
      is_published: true,
      industries: ['Mobile Apps', 'E-commerce']
    },
    {
      id: '6',
      name: 'Lisa Pettersson',
      email: 'lisa.pettersson@example.com',
      phone: '+46 73 888 9999',
      location: 'Västerås, Sweden',
      title: 'UX/UI Designer & Frontend Developer',
      tagline: 'Design-driven frontend development',
      skills: ['React', 'TypeScript', 'Figma', 'CSS', 'HTML'],
      roles: ['Frontend Developer', 'UX/UI Designer'],
      experience: '6 years',
      experience_years: 6,
      certifications: ['Google UX Design', 'Adobe Certified Expert'],
      languages: ['Swedish', 'English'],
      rating: 4.9,
      projects: 20,
      rate: '880 SEK/hour',
      hourly_rate: 880,
      availability: 'Available',
      lastActive: 'Today',
      last_active: 'Today',
      cv: '',
      communicationStyle: 'Visual and collaborative',
      communication_style: 'Visual and collaborative',
      workStyle: 'Design-first development approach',
      work_style: 'Design-first development approach',
      teamFit: 'Bridges design and development teams',
      team_fit: 'Bridges design and development teams',
      culturalFit: 5,
      cultural_fit: 5,
      adaptability: 4,
      leadership: 4,
      personalityTraits: ['Creative', 'Empathetic', 'Detail-oriented'],
      personality_traits: ['Creative', 'Empathetic', 'Detail-oriented'],
      values: ['User Experience', 'Accessibility', 'Innovation'],
      linkedin_url: 'https://linkedin.com/in/lisa-pettersson',
      thought_leadership_score: 7.8,
      type: 'existing',
      created_at: '2024-01-06',
      updated_at: '2024-01-20',
      visibility_status: 'public',
      is_published: true,
      industries: ['Design', 'Technology']
    },
    {
      id: '7',
      name: 'Andreas Holm',
      email: 'andreas.holm@example.com',
      phone: '+46 70 000 1111',
      location: 'Örebro, Sweden',
      title: 'Data Engineer',
      tagline: 'Big data and analytics specialist',
      skills: ['Python', 'Apache Spark', 'SQL', 'Airflow', 'AWS'],
      roles: ['Data Engineer', 'Analytics Engineer'],
      experience: '5 years',
      experience_years: 5,
      certifications: ['AWS Big Data', 'Google Data Engineer'],
      languages: ['Swedish', 'English', 'Norwegian'],
      rating: 4.7,
      projects: 16,
      rate: '890 SEK/hour',
      hourly_rate: 890,
      availability: 'Available from April 2025',
      lastActive: '1 day ago',
      last_active: '1 day ago',
      cv: '',
      communicationStyle: 'Analytical and thorough',
      communication_style: 'Analytical and thorough',
      workStyle: 'Data-driven decision making',
      work_style: 'Data-driven decision making',
      teamFit: 'Excellent mentor and code reviewer',
      team_fit: 'Excellent mentor and code reviewer',
      culturalFit: 4,
      cultural_fit: 4,
      adaptability: 3,
      leadership: 4,
      personalityTraits: ['Analytical', 'Thorough', 'Patient'],
      personality_traits: ['Analytical', 'Thorough', 'Patient'],
      values: ['Data Quality', 'Best Practices', 'Knowledge Sharing'],
      linkedin_url: 'https://linkedin.com/in/andreas-holm',
      thought_leadership_score: 8.0,
      type: 'existing',
      created_at: '2024-01-07',
      updated_at: '2024-01-21',
      visibility_status: 'public',
      is_published: true,
      industries: ['Data Analytics', 'Finance']
    }
  ]);

  const addConsultant = useCallback((newConsultant: Consultant) => {
    // This would typically make an API call
    console.log('Adding consultant:', newConsultant);
  }, []);

  const updateConsultant = useCallback((id: string, updates: Partial<Consultant>) => {
    // This would typically make an API call
    console.log('Updating consultant:', id, updates);
  }, []);

  const deleteConsultant = useCallback((id: string) => {
    // This would typically make an API call
    console.log('Deleting consultant:', id);
  }, []);

  return {
    consultants,
    addConsultant,
    updateConsultant,
    deleteConsultant,
    loading: false,
    error: null
  };
};

export default useConsultants;
