
import React, { useState } from 'react';
import { Users, Briefcase, Target, TrendingUp, Upload, Search, Filter, Sparkles, Star, Check, Mail, FileDown, Clock, DollarSign, User, MapPin, Calendar } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import ConsultantsTab from '../components/ConsultantsTab';
import CreateAssignmentForm from '../components/CreateAssignmentForm';
import Dashboard from '../components/Dashboard';
import { useConsultants } from '../hooks/useConsultants';
import { Consultant, Assignment, Match } from '../types/consultant';
import { useToast } from "@/hooks/use-toast";

// AI Matching function
const findMatches = (consultants: Consultant[], assignment: Assignment): Match[] => {
  console.log("🤖 AI Matching Started for:", assignment.title);
  console.log("📊 Analyzing", consultants.length, "consultants...");
  
  const matches: Match[] = [];
  
  consultants.forEach(consultant => {
    // Calculate exact skill matches
    const exactMatches = consultant.skills.filter(skill => 
      assignment.requiredSkills.some(reqSkill => 
        skill.toLowerCase() === reqSkill.toLowerCase()
      )
    );
    
    // Calculate partial skill matches
    const partialMatches = consultant.skills.filter(skill => 
      assignment.requiredSkills.some(reqSkill => 
        skill.toLowerCase().includes(reqSkill.toLowerCase()) || 
        reqSkill.toLowerCase().includes(skill.toLowerCase())
      )
    ).filter(skill => !exactMatches.includes(skill));
    
    const totalMatchedSkills = [...exactMatches, ...partialMatches];
    
    // Enhanced scoring algorithm
    let score = 0;
    
    // 1. Skills matching (50% of total score)
    const exactMatchWeight = 30; // 30% for exact matches
    const partialMatchWeight = 20; // 20% for partial matches
    
    const exactMatchScore = (exactMatches.length / assignment.requiredSkills.length) * exactMatchWeight;
    const partialMatchScore = (partialMatches.length / assignment.requiredSkills.length) * partialMatchWeight;
    score += exactMatchScore + partialMatchScore;
    
    // 2. Experience factor (20% of total score)
    const experienceYears = parseInt(consultant.experience.replace(/\D/g, '')) || 0;
    const experienceScore = Math.min((experienceYears / 10) * 20, 20); // Max 20 points
    score += experienceScore;
    
    // 3. Rating factor (15% of total score)
    const ratingScore = (consultant.rating / 5) * 15;
    score += ratingScore;
    
    // 4. Cultural fit and availability (15% of total score)
    const culturalScore = (consultant.culturalFit / 5) * 10;
    const availabilityScore = consultant.availability.toLowerCase().includes('available') ? 5 : 2;
    score += culturalScore + availabilityScore;
    
    // Only include consultants with meaningful matches
    if (totalMatchedSkills.length > 0) {
      // Generate personalized cover letter
      const letter = `Subject: Perfect Match for ${assignment.title} at ${assignment.company}

Dear Hiring Manager,

I'm ${consultant.name}, a ${consultant.roles[0]} with ${consultant.experience} of hands-on experience. Your ${assignment.title} project perfectly aligns with my expertise and career goals.

🎯 Why I'm Perfect for This Role:

Technical Match (${Math.round(score)}%):
${exactMatches.map(skill => `✅ Expert in ${skill}`).join('\n')}
${partialMatches.map(skill => `✅ Expert in ${skill}`).join('\n')}

Track Record:
• ${consultant.projects} projects delivered on-time and on-budget
• ${consultant.rating}/5.0 client satisfaction rating
• ${consultant.certifications.slice(0, 2).join(', ')} certified

Leadership & Team Dynamics:
• ${consultant.communicationStyle}
• ${consultant.teamFit}
• ${consultant.values.join(', ')} values align with your team culture

💰 Investment: ${consultant.rate} (fits within your ${assignment.budget} budget)
📅 Start Date: Ready for ${assignment.startDate}
⚡ Response Time: Active ${consultant.lastActive}

I'd love to discuss how my experience can accelerate your project timeline and ensure technical excellence. Available for a call this week!

Cheers,
${consultant.name}

Contact: ${consultant.email} | ${consultant.phone}
Portfolio: Available upon request

P.S. - This personalized application was generated by AI but reflects my genuine interest and qualifications! 🤖✨`;

      const humanFactorsScore = Math.round((consultant.culturalFit + consultant.adaptability + consultant.leadership) / 3 * 20);
      
      matches.push({
        consultant,
        score: Math.round(Math.min(score, 100)), // Cap at 100%
        matchedSkills: totalMatchedSkills,
        humanFactorsScore,
        culturalMatch: Math.round((consultant.culturalFit / 5) * 100),
        communicationMatch: Math.round(85 + Math.random() * 15), // Simulated
        valuesAlignment: Math.round(80 + Math.random() * 20), // Simulated  
        estimatedSavings: Math.floor(Math.random() * 30000) + 5000,
        responseTime: Math.floor(Math.random() * 8) + 2,
        letter
      });
    }
  });
  
  // Sort by score (highest first) and return top matches
  const sortedMatches = matches.sort((a, b) => b.score - a.score);
  console.log("✅ Found", sortedMatches.length, "matches, top score:", sortedMatches[0]?.score + "%");
  
  return sortedMatches;
};

const DashboardPage = () => {
  const { consultants, isProcessing, uploadCV } = useConsultants();
  const { toast } = useToast();
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [matches, setMatches] = useState<Match[]>([]);
  const [isMatching, setIsMatching] = useState(false);
  const [selectedAssignment, setSelectedAssignment] = useState<Assignment | null>(null);
  const [assignments, setAssignments] = useState<Assignment[]>([
    {
      id: 1,
      title: 'React Developer',
      description: 'Frontend developer for e-commerce project',
      requiredSkills: ['React', 'TypeScript'],
      duration: '6 months',
      startDate: '2024-07-01',
      workload: 'Full-time',
      budget: '800-1000 SEK/hour',
      company: 'TechCorp AB',
      industry: 'E-commerce',
      teamSize: '8 people',
      remote: 'Hybrid',
      urgency: 'Medium',
      clientLogo: '🛍️',
      desiredCommunicationStyle: 'Collaborative and direct',
      teamCulture: 'Agile, innovation-focused',
      requiredValues: ['Innovation', 'Quality'],
      leadershipLevel: 3,
      teamDynamics: 'Cross-functional team'
    },
    {
      id: 2,
      title: 'UX Designer',
      description: 'Design user-friendly mobile app',
      requiredSkills: ['UX Design', 'Prototyping'],
      duration: '3 months',
      startDate: '2024-06-15',
      workload: 'Part-time',
      budget: '600-800 SEK/hour',
      company: 'DesignStudio',
      industry: 'Mobile Apps',
      teamSize: '5 people',
      remote: 'Remote',
      urgency: 'High',
      clientLogo: '🎨',
      desiredCommunicationStyle: 'Creative and collaborative',
      teamCulture: 'Design-focused, flexible',
      requiredValues: ['Creativity', 'User Focus'],
      leadershipLevel: 2,
      teamDynamics: 'Small design team'
    }
  ]);

  // Split consultants by type
  const existingConsultants = consultants.filter(consultant => consultant.type === 'existing');
  const newConsultants = consultants.filter(consultant => consultant.type === 'new');

  const handleFindMatches = async (assignment: Assignment) => {
    console.log("🚀 Starting AI matching for assignment:", assignment.title);
    console.log("📋 Assignment details:", assignment);
    console.log("👥 Available consultants:", consultants.length);
    
    setIsMatching(true);
    setSelectedAssignment(assignment);
    
    try {
      // Simulate AI processing time
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const foundMatches = findMatches(consultants, assignment);
      console.log("🎯 Matches found:", foundMatches.length);
      
      setMatches(foundMatches);
      setIsMatching(false);
      
      toast({
        title: "🤖 AI Matching Complete",
        description: `Found ${foundMatches.length} potential matches for ${assignment.title}`,
      });
    } catch (error) {
      console.error("❌ Error during matching:", error);
      setIsMatching(false);
      toast({
        title: "Error",
        description: "Something went wrong during matching. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleSelectMatch = (match: Match) => {
    console.log("Selecting match:", match);
    if (selectedAssignment) {
      setAssignments(prev => prev.filter(a => a.id !== selectedAssignment.id));
      setMatches([]);
      setSelectedAssignment(null);
      
      toast({
        title: "Match Selected",
        description: `${match.consultant.name} has been matched to ${selectedAssignment.title}`,
      });
    }
  };

  const handleMatch = (assignment: Assignment) => {
    handleFindMatches(assignment);
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      try {
        await uploadCV(file);
        toast({
          title: "CV Uploaded Successfully",
          description: "The consultant has been added to the database.",
        });
      } catch (error) {
        toast({
          title: "Upload Failed",
          description: "There was an error uploading the CV.",
          variant: "destructive",
        });
      }
    }
  };

  const handleAssignmentCreated = (newAssignment: Assignment) => {
    const assignmentWithId = {
      ...newAssignment,
      id: Date.now(),
    };
    setAssignments(prev => [...prev, assignmentWithId]);
    setShowCreateForm(false);
    toast({
      title: "Assignment Created",
      description: "New assignment has been added successfully.",
    });
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Header */}
        <div className="text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            AI-Driven Consultant Matching Platform
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Match consultants with assignments using advanced AI that analyzes both technical skills and soft factors
          </p>
        </div>

        {/* Main Content */}
        <Tabs defaultValue="dashboard" className="space-y-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <TabsList className="grid w-full sm:w-auto grid-cols-3">
              <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
              <TabsTrigger value="consultants">Consultants</TabsTrigger>
              <TabsTrigger value="assignments">Assignments</TabsTrigger>
            </TabsList>
            
            <div className="flex gap-2">
              <Button 
                onClick={() => setShowCreateForm(true)}
                className="bg-blue-600 hover:bg-blue-700"
              >
                <Briefcase className="h-4 w-4 mr-2" />
                New Assignment
              </Button>
              
              <div className="relative">
                <input
                  type="file"
                  accept=".pdf,.doc,.docx"
                  onChange={handleFileUpload}
                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                  disabled={isProcessing}
                />
                <Button 
                  variant="outline"
                  disabled={isProcessing}
                  className="relative"
                >
                  <Upload className="h-4 w-4 mr-2" />
                  {isProcessing ? 'Processing...' : 'Upload CV'}
                </Button>
              </div>
            </div>
          </div>

          <TabsContent value="dashboard" className="space-y-6">
            <Dashboard 
              consultants={consultants}
              assignments={assignments}
              onMatch={handleMatch}
              onFileUpload={handleFileUpload}
              onAssignmentCreated={handleAssignmentCreated}
            />
          </TabsContent>

          <TabsContent value="consultants" className="space-y-6">
            <ConsultantsTab 
              existingConsultants={existingConsultants}
              newConsultants={newConsultants}
              isMatching={isProcessing}
              onFileUpload={handleFileUpload}
            />
          </TabsContent>

          <TabsContent value="assignments" className="space-y-6">
            <div className="space-y-8">
              {/* Show matches if available */}
              {matches.length > 0 && selectedAssignment ? (
                <div className="space-y-6">
                  {/* Header with assignment info */}
                  <div className="bg-white rounded-xl shadow-sm border p-6">
                    <div className="flex items-center justify-between mb-4">
                      <div>
                        <h1 className="text-2xl font-bold text-gray-900">AI Matching Results</h1>
                        <p className="text-gray-600">Results for: {selectedAssignment.title}</p>
                      </div>
                      <div className="flex items-center space-x-4">
                        <div className="flex items-center space-x-2 text-sm text-gray-600">
                          <div className="w-3 h-3 bg-blue-100 rounded-full flex items-center justify-center">
                            <div className="w-1.5 h-1.5 bg-blue-600 rounded-full"></div>
                          </div>
                          <span>Sorted by AI confidence score</span>
                        </div>
                        <div className="flex items-center space-x-2 text-sm text-green-600">
                          <Sparkles className="h-4 w-4" />
                          <span>Matched {matches.length} consultants in 12 seconds</span>
                        </div>
                        <button
                          onClick={() => {
                            setMatches([]);
                            setSelectedAssignment(null);
                          }}
                          className="text-gray-500 hover:text-gray-700 text-lg"
                        >
                          ✕
                        </button>
                      </div>
                    </div>
                  </div>

                  {/* Match Results */}
                  <div className="space-y-6">
                    {matches.slice(0, 5).map((match, index) => (
                      <div key={match.consultant.id} className="bg-white rounded-xl shadow-sm border overflow-hidden">
                        {/* Match Header */}
                        <div className="p-6 border-b border-gray-100">
                          <div className="flex items-start justify-between">
                            <div className="flex items-center space-x-4">
                              <div className="flex items-center space-x-3">
                                <div className="bg-orange-100 text-orange-600 w-12 h-12 rounded-full flex items-center justify-center font-bold text-lg">
                                  #{index + 1}
                                </div>
                                <div className="bg-gradient-to-r from-blue-500 to-purple-500 text-white w-12 h-12 rounded-full flex items-center justify-center font-bold text-lg">
                                  {match.consultant.name.split(' ').map(n => n[0]).join('')}
                                </div>
                              </div>
                              <div>
                                <h3 className="text-xl font-bold text-gray-900">{match.consultant.name}</h3>
                                <p className="text-gray-600">{match.consultant.roles[0]} • {match.consultant.location}</p>
                              </div>
                            </div>
                            <div className="text-right">
                              <div className="flex items-center space-x-2 mb-2">
                                <Star className="h-5 w-5 text-blue-500" />
                                <span className="text-2xl font-bold text-blue-600">{match.score}% Match</span>
                              </div>
                              <p className="text-sm text-gray-600">AI Confidence Score</p>
                            </div>
                          </div>
                        </div>

                        {/* Matching Skills */}
                        <div className="p-6 border-b border-gray-100">
                          <div className="flex items-center space-x-2 mb-3">
                            <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                            <h4 className="font-semibold text-gray-900">Matching Skills</h4>
                          </div>
                          <div className="flex flex-wrap gap-2">
                            {match.matchedSkills.map((skill, skillIndex) => (
                              <div key={skillIndex} className="flex items-center space-x-1 bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm">
                                <Check className="h-3 w-3" />
                                <span>{skill}</span>
                              </div>
                            ))}
                          </div>
                        </div>

                        {/* Action Button */}
                        <div className="p-6 bg-gray-50 border-t">
                          <button
                            onClick={() => handleSelectMatch(match)}
                            className="w-full bg-green-600 text-white py-3 px-4 rounded-lg hover:bg-green-700 transition-colors font-semibold"
                          >
                            Select This Match
                          </button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                /* Assignments Grid */
                <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                  {assignments.map((assignment) => (
                    <Card key={assignment.id} className="hover:shadow-md transition-shadow">
                      <CardHeader>
                        <div className="flex justify-between items-start">
                          <div>
                            <CardTitle className="text-xl">{assignment.title}</CardTitle>
                            <p className="text-gray-600 mt-2">{assignment.description}</p>
                          </div>
                          <div className="text-right">
                            <div className="text-2xl mb-2">{assignment.clientLogo}</div>
                            <p className="font-semibold text-gray-900">{assignment.company}</p>
                            <p className="text-sm text-gray-500">{assignment.industry}</p>
                          </div>
                        </div>
                      </CardHeader>
                      
                      <CardContent>
                        <div className="grid md:grid-cols-1 gap-6">
                          <div className="space-y-4">
                            <div>
                              <h4 className="font-semibold mb-2">Required Skills</h4>
                              <div className="flex flex-wrap gap-2">
                                {assignment.requiredSkills.map((skill, index) => (
                                  <Badge key={index} variant="secondary">{skill}</Badge>
                                ))}
                              </div>
                            </div>
                            
                            <div>
                              <h4 className="font-semibold mb-2">Assignment Details</h4>
                              <div className="space-y-1 text-sm text-gray-600">
                                <p><strong>Duration:</strong> {assignment.duration}</p>
                                <p><strong>Budget:</strong> {assignment.budget}</p>
                                <p><strong>Remote:</strong> {assignment.remote}</p>
                              </div>
                            </div>
                            
                            <div className="flex gap-2 pt-4">
                              <Button 
                                onClick={() => {
                                  console.log("🔍 Find Matches button clicked for:", assignment.title);
                                  handleFindMatches(assignment);
                                }}
                                disabled={isMatching}
                                className="flex-1 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
                              >
                                {isMatching && selectedAssignment?.id === assignment.id ? (
                                  <>
                                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                                    Finding Matches...
                                  </>
                                ) : (
                                  <>
                                    <Sparkles className="h-4 w-4 mr-2" />
                                    Find AI Match
                                  </>
                                )}
                              </Button>
                              <Badge 
                                variant={assignment.urgency === 'High' ? 'destructive' : assignment.urgency === 'Medium' ? 'default' : 'secondary'}
                              >
                                {assignment.urgency}
                              </Badge>
                            </div>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </div>
          </TabsContent>
        </Tabs>

        {/* Create Assignment Modal */}
        {showCreateForm && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
              <CreateAssignmentForm
                onAssignmentCreated={handleAssignmentCreated}
                onCancel={() => setShowCreateForm(false)}
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DashboardPage;
