
import { Consultant, Assignment, Match } from '../types/consultant';

export const calculateMatch = (consultant: Consultant, assignment: Assignment): number => {
  const consultantSkills = consultant.skills.map(s => s.toLowerCase());
  const requiredSkills = assignment.requiredSkills.map(s => s.toLowerCase());
  
  const matchingSkills = consultantSkills.filter(skill => 
    requiredSkills.some(required => 
      skill.includes(required.toLowerCase()) || required.toLowerCase().includes(skill)
    )
  );
  
  const skillScore = (matchingSkills.length / requiredSkills.length) * 60;
  const experienceScore = Math.min(parseInt(consultant.experience) * 2.5, 25);
  const availabilityScore = consultant.availability === 'Available now' ? 10 : 5;
  const ratingScore = consultant.rating * 1;
  
  return Math.min(Math.round(skillScore + experienceScore + availabilityScore + ratingScore), 98);
};

export const findMatches = (consultants: Consultant[], assignment: Assignment): Match[] => {
  return consultants.map(consultant => {
    const score = calculateMatch(consultant, assignment);
    const letter = generateMotivationLetter(consultant, assignment, score);
    
    const matchedSkills = consultant.skills.filter(skill => 
      assignment.requiredSkills.some(req => 
        skill.toLowerCase().includes(req.toLowerCase()) || 
        req.toLowerCase().includes(skill.toLowerCase())
      )
    );

    return {
      consultant,
      score,
      letter,
      matchedSkills,
      estimatedSavings: Math.floor(score * 100 + Math.random() * 500),
      responseTime: Math.floor(Math.random() * 24) + 1,
      culturalMatch: Math.floor(Math.random() * 30) + 70,
      communicationMatch: Math.floor(Math.random() * 25) + 75,
      valuesAlignment: Math.floor(Math.random() * 20) + 80,
      humanFactorsScore: Math.floor(Math.random() * 15) + 85
    };
  }).sort((a, b) => b.score - a.score);
};

export const generateMotivationLetter = (consultant: Consultant, assignment: Assignment, matchScore: number): string => {
  const templates = [
    `Subject: Application for ${assignment.title} - ${consultant.name}

Dear Hiring Team at ${assignment.company},

I am excited to apply for the ${assignment.title} position. With my ${consultant.experience} of experience and proven track record of ${consultant.projects} successful projects, I am confident I can deliver exceptional value to your ${assignment.industry.toLowerCase()} initiative.

🔧 Technical Alignment:
My expertise in ${consultant.skills.filter(skill => 
  assignment.requiredSkills.some(req => skill.toLowerCase().includes(req.toLowerCase()) || req.toLowerCase().includes(skill.toLowerCase()))
).join(', ')} directly matches your technical requirements. I have successfully delivered similar solutions for enterprise clients, maintaining a ${consultant.rating}/5.0 client satisfaction rating.

💼 Project Experience:
• ${consultant.projects} completed projects with 100% delivery rate
• Specialized in ${consultant.roles[0].toLowerCase()} roles
• ${consultant.certifications.join(' and ')} certified
• Fluent in ${consultant.languages.join(', ')}

📍 Logistics:
• Location: ${consultant.location} (${assignment.remote} compatible)
• Availability: ${consultant.availability} from ${assignment.startDate}
• Rate: ${consultant.rate} (within your ${assignment.budget} budget)
• Team collaboration: Experienced with ${assignment.teamSize} teams

I am available for an immediate interview and can start on your preferred timeline. My recent work includes similar ${assignment.industry.toLowerCase()} projects where I delivered measurable ROI through technical excellence.

Thank you for considering my application. I look forward to contributing to ${assignment.company}'s success.

Best regards,
${consultant.name}
📧 ${consultant.email}
📱 ${consultant.phone}

---
Generated by AI in 0.3 seconds | Match Score: ${matchScore}% | Last updated: ${consultant.lastActive}`,

    `Application: ${assignment.title} | ${consultant.name}

Hello ${assignment.company} Team! 👋

I'm ${consultant.name}, a ${consultant.roles[0]} with ${consultant.experience} of hands-on experience. Your ${assignment.title} project perfectly aligns with my expertise and career goals.

🎯 Why I'm Perfect for This Role:

Technical Match (${matchScore}%):
✅ ${consultant.skills.filter(skill => 
  assignment.requiredSkills.some(req => skill.toLowerCase().includes(req.toLowerCase()) || req.toLowerCase().includes(skill.toLowerCase()))
).map(skill => `Expert in ${skill}`).join('\n✅ ')}

Track Record:
• ${consultant.projects} projects delivered on-time and on-budget
• ${consultant.rating}/5.0 average client rating
• ${consultant.certifications.join(' & ')} certified professional
• Based in ${consultant.location}, available for ${assignment.remote.toLowerCase()} work

Project Fit:
• Duration: ${assignment.duration} ✅ (I specialize in ${assignment.duration.includes('6') ? 'medium-term' : 'long-term'} engagements)
• Workload: ${assignment.workload} ✅ (Currently ${consultant.availability.toLowerCase()})
• Industry: ${assignment.industry} ✅ (Previous experience with similar solutions)
• Team Size: ${assignment.teamSize} ✅ (Love collaborative environments)

🚀 What I Bring Beyond Technical Skills:
• Proactive communication and regular progress updates
• Documentation and knowledge transfer focus
• Mentoring junior developers when needed
• Business-oriented approach to technical decisions

💰 Investment: ${consultant.rate} (fits within your ${assignment.budget} budget)
📅 Start Date: Ready for ${assignment.startDate}
⚡ Response Time: Active ${consultant.lastActive}

I'd love to discuss how my experience can accelerate your project timeline and ensure technical excellence. Available for a call this week!

Cheers,
${consultant.name}

Contact: ${consultant.email} | ${consultant.phone}
Portfolio: Available upon request

P.S. - This personalized application was generated by AI but reflects my genuine interest and qualifications! 🤖✨`
  ];
  
  return templates[Math.floor(Math.random() * templates.length)];
};
