-- Create demo consultant user profile and consultant record
-- First insert into user_profiles
INSERT INTO public.user_profiles (
  id, 
  user_id, 
  full_name, 
  email, 
  phone, 
  title, 
  personal_tagline, 
  rate_preference, 
  availability,
  years_of_experience,
  visibility_toggle
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001'::uuid,
  'Anna Lindström - Demo Konsult',
  'demo-konsult@matchwise.tech',
  '+46 70 123 45 67',
  'Senior Fullstack Developer',
  'Passionerad utvecklare med fokus på modern webbutveckling och användarupplevelse',
  950,
  'Tillgänglig',
  8,
  true
) ON CONFLICT (user_id) DO NOTHING;

-- Then insert consultant record linked to the demo user
INSERT INTO public.consultants (
  id,
  user_id,
  name,
  email,
  phone,
  location,
  title,
  tagline,
  experience_years,
  hourly_rate,
  rating,
  projects_completed,
  availability,
  skills,
  primary_tech_stack,
  secondary_tech_stack,
  certifications,
  values,
  personality_traits,
  communication_style,
  work_style,
  industries,
  top_values,
  thought_leadership_score,
  market_rate_current,
  market_rate_optimized,
  profile_completeness,
  visibility_status,
  is_published,
  type,
  last_active,
  linkedin_url,
  cultural_fit,
  adaptability,
  leadership
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001'::uuid,
  'Anna Lindström - Demo Konsult',
  'demo-konsult@matchwise.tech',
  '+46 70 123 45 67',
  'Stockholm, Sverige',
  'Senior Fullstack Developer',
  'Passionerad utvecklare med fokus på modern webbutveckling och användarupplevelse',
  8,
  950,
  4.8,
  24,
  'Tillgänglig',
  ARRAY['React', 'TypeScript', 'Node.js', 'Python', 'AWS', 'Docker', 'PostgreSQL', 'GraphQL', 'MongoDB'],
  ARRAY['React', 'TypeScript', 'Node.js'],
  ARRAY['Python', 'AWS', 'Docker'],
  ARRAY['AWS Solutions Architect', 'Certified Scrum Master', 'React Professional'],
  ARRAY['Innovation', 'Kvalitet', 'Teamwork', 'Kontinuerlig utveckling'],
  ARRAY['Analytisk', 'Problemlösare', 'Empatisk', 'Proaktiv', 'Kreativ'],
  'Tydlig och direkt kommunikation med fokus på samarbete',
  'Agile-fokuserad med stark problemlösningsförmåga',
  ARRAY['Fintech', 'E-commerce', 'SaaS', 'Healthtech'],
  ARRAY['Innovation', 'Kvalitet', 'Användarfokus'],
  85,
  850,
  1100,
  95,
  'public',
  true,
  'existing',
  'Today',
  'https://linkedin.com/in/anna-lindstrom-demo',
  5,
  5,
  4
) ON CONFLICT (user_id) DO NOTHING;

-- Create AI analysis for the demo consultant
INSERT INTO public.ai_analysis (
  id,
  user_profile_id,
  analysis_data,
  thought_leadership_score,
  analysis_complete,
  tech_stack_primary,
  tech_stack_secondary,
  certifications,
  industries,
  top_values,
  personality_traits,
  communication_style,
  tone_of_voice,
  linkedin_engagement_level,
  brand_themes,
  cv_tips,
  linkedin_tips,
  certification_recommendations,
  suggested_learning_paths
) VALUES (
  gen_random_uuid(),
  (SELECT id FROM public.user_profiles WHERE user_id = '00000000-0000-0000-0000-000000000001'::uuid),
  jsonb_build_object(
    'overall_score', 92,
    'technical_expertise', 95,
    'communication_skills', 88,
    'leadership_potential', 85,
    'market_positioning', 90
  ),
  85,
  true,
  ARRAY['React', 'TypeScript', 'Node.js'],
  ARRAY['Python', 'AWS', 'Docker'],
  ARRAY['AWS Solutions Architect', 'Certified Scrum Master', 'React Professional'],
  ARRAY['Fintech', 'E-commerce', 'SaaS', 'Healthtech'],
  ARRAY['Innovation', 'Kvalitet', 'Användarfokus'],
  ARRAY['Analytisk', 'Problemlösare', 'Empatisk', 'Proaktiv'],
  'Tydlig och direkt kommunikation med fokus på samarbete',
  'Professionell och engagerad',
  'Hög',
  ARRAY['Modern utveckling', 'Användarfokus', 'Innovation'],
  ARRAY['Lägg till mer specifika projektresultat', 'Inkludera teknisk arkitektur-erfarenhet'],
  ARRAY['Dela fler tekniska insights', 'Engagera mer i community diskussioner'],
  ARRAY['Kubernetes', 'Cloud Architecture', 'DevOps'],
  ARRAY['Advanced React Patterns', 'System Design', 'Team Leadership']
) ON CONFLICT (user_profile_id) DO NOTHING;